webtalk_init -webtalk_dir C:/Users/trith/HFT_sim/HFT_sim_FPGA/hft_sim/hft_sim.sim/sim_1/behav/xsim/xsim.dir/MAC_rx_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Aug 18 01:05:31 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f7566d77-3f3b-46e0-987f-6f7afdb31f7e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "0656f8c6f92849c0ae222b87d342d1ef" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "9" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 7840HS w/ Radeon 780M Graphics     " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3793 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "285 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "11432_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1183542038 -regid "" -xml C:/Users/trith/HFT_sim/HFT_sim_FPGA/hft_sim/hft_sim.sim/sim_1/behav/xsim/xsim.dir/MAC_rx_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/trith/HFT_sim/HFT_sim_FPGA/hft_sim/hft_sim.sim/sim_1/behav/xsim/xsim.dir/MAC_rx_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/trith/HFT_sim/HFT_sim_FPGA/hft_sim/hft_sim.sim/sim_1/behav/xsim/xsim.dir/MAC_rx_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
