set_property SRC_FILE_INFO {cfile:C:/Users/trith/HFT_sim/HFT_sim_FPGA/hft_sim/hft_sim.srcs/constrs_1/new/crc_constraint.xdc rfile:../../../hft_sim.srcs/constrs_1/new/crc_constraint.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_clock -name CLK156 -period 6.400 [get_ports CLK]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_ports nRST] -to [all_registers]
