// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vether_simulation.h for the primary calling header

#include "Vether_simulation__pch.h"
#include "Vether_simulation__Syms.h"
#include "Vether_simulation___024root.h"

VL_ATTR_COLD void Vether_simulation___024root___eval_static(Vether_simulation___024root* vlSelf) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vether_simulation___024root___eval_static\n"); );
    Vether_simulation__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__svr_inst__mac_rx____PVT__mac_dest_addr__0 
        = vlSymsp->TOP__ether_simulation__svr_inst__mac_rx.__PVT__mac_dest_addr;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__clt_inst__mac_rx____PVT__mac_dest_addr__0 
        = vlSymsp->TOP__ether_simulation__clt_inst__mac_rx.__PVT__mac_dest_addr;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__svr_inst__mac_rx____PVT__mac_dest_addr__1 
        = vlSymsp->TOP__ether_simulation__svr_inst__mac_rx.__PVT__mac_dest_addr;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__clt_inst__mac_rx____PVT__mac_dest_addr__1 
        = vlSymsp->TOP__ether_simulation__clt_inst__mac_rx.__PVT__mac_dest_addr;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__svr_inst__mac_rx____PVT__mac_dest_addr__2 
        = vlSymsp->TOP__ether_simulation__svr_inst__mac_rx.__PVT__mac_dest_addr;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__clt_inst__mac_rx____PVT__mac_dest_addr__2 
        = vlSymsp->TOP__ether_simulation__clt_inst__mac_rx.__PVT__mac_dest_addr;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__svr_inst__u_payload_fifo____PVT__CLK__0 
        = vlSymsp->TOP__ether_simulation__svr_inst__u_payload_fifo.__PVT__CLK;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__svr_inst__u_payload_fifo____PVT__nRST__0 
        = vlSymsp->TOP__ether_simulation__svr_inst__u_payload_fifo.__PVT__nRST;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__clt_inst__u_payload_fifo____PVT__CLK__0 
        = vlSymsp->TOP__ether_simulation__clt_inst__u_payload_fifo.__PVT__CLK;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__clt_inst__u_payload_fifo____PVT__nRST__0 
        = vlSymsp->TOP__ether_simulation__clt_inst__u_payload_fifo.__PVT__nRST;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__svr_inst__ip_rx____PVT__CLK__0 
        = vlSymsp->TOP__ether_simulation__svr_inst__ip_rx.__PVT__CLK;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__svr_inst__ip_rx____PVT__nRST__0 
        = vlSymsp->TOP__ether_simulation__svr_inst__ip_rx.__PVT__nRST;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__clt_inst__ip_rx____PVT__CLK__0 
        = vlSymsp->TOP__ether_simulation__clt_inst__ip_rx.__PVT__CLK;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__clt_inst__ip_rx____PVT__nRST__0 
        = vlSymsp->TOP__ether_simulation__clt_inst__ip_rx.__PVT__nRST;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__svr_inst__mac_rx____PVT__CLK__0 
        = vlSymsp->TOP__ether_simulation__svr_inst__mac_rx.__PVT__CLK;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__svr_inst__mac_rx____PVT__nRST__0 
        = vlSymsp->TOP__ether_simulation__svr_inst__mac_rx.__PVT__nRST;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__clt_inst__mac_rx____PVT__CLK__0 
        = vlSymsp->TOP__ether_simulation__clt_inst__mac_rx.__PVT__CLK;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__clt_inst__mac_rx____PVT__nRST__0 
        = vlSymsp->TOP__ether_simulation__clt_inst__mac_rx.__PVT__nRST;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__svr_inst__mac_tx____PVT__CLK__0 
        = vlSymsp->TOP__ether_simulation__svr_inst__mac_tx.__PVT__CLK;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__svr_inst__mac_tx____PVT__nRST__0 
        = vlSymsp->TOP__ether_simulation__svr_inst__mac_tx.__PVT__nRST;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__clt_inst__mac_tx____PVT__CLK__0 
        = vlSymsp->TOP__ether_simulation__clt_inst__mac_tx.__PVT__CLK;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__clt_inst__mac_tx____PVT__nRST__0 
        = vlSymsp->TOP__ether_simulation__clt_inst__mac_tx.__PVT__nRST;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__svr_inst__ip_tx____PVT__CLK__0 
        = vlSymsp->TOP__ether_simulation__svr_inst__ip_tx.__PVT__CLK;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__svr_inst__ip_tx____PVT__nRST__0 
        = vlSymsp->TOP__ether_simulation__svr_inst__ip_tx.__PVT__nRST;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__clt_inst__ip_tx____PVT__CLK__0 
        = vlSymsp->TOP__ether_simulation__clt_inst__ip_tx.__PVT__CLK;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__clt_inst__ip_tx____PVT__nRST__0 
        = vlSymsp->TOP__ether_simulation__clt_inst__ip_tx.__PVT__nRST;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__svr_inst__u_fifo_tx____PVT__CLK__0 
        = vlSymsp->TOP__ether_simulation__svr_inst__u_fifo_tx.__PVT__CLK;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__svr_inst__u_fifo_tx____PVT__nRST__0 
        = vlSymsp->TOP__ether_simulation__svr_inst__u_fifo_tx.__PVT__nRST;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__clt_inst__u_fifo_tx____PVT__CLK__0 
        = vlSymsp->TOP__ether_simulation__clt_inst__u_fifo_tx.__PVT__CLK;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__clt_inst__u_fifo_tx____PVT__nRST__0 
        = vlSymsp->TOP__ether_simulation__clt_inst__u_fifo_tx.__PVT__nRST;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__svr_inst__u_tcp__inst____PVT__CLK__0 
        = vlSymsp->TOP__ether_simulation__svr_inst__u_tcp__inst.__PVT__CLK;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__svr_inst__u_tcp__inst____PVT__nRST__0 
        = vlSymsp->TOP__ether_simulation__svr_inst__u_tcp__inst.__PVT__nRST;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__clt_inst__u_tcp__inst____PVT__CLK__0 
        = vlSymsp->TOP__ether_simulation__clt_inst__u_tcp__inst.__PVT__CLK;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__clt_inst__u_tcp__inst____PVT__nRST__0 
        = vlSymsp->TOP__ether_simulation__clt_inst__u_tcp__inst.__PVT__nRST;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__svr_inst__u_tcp__TCP_tx____PVT__CLK__0 
        = vlSymsp->TOP__ether_simulation__svr_inst__u_tcp__TCP_tx.__PVT__CLK;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__svr_inst__u_tcp__TCP_tx____PVT__nRST__0 
        = vlSymsp->TOP__ether_simulation__svr_inst__u_tcp__TCP_tx.__PVT__nRST;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__clt_inst__u_tcp__TCP_tx____PVT__CLK__0 
        = vlSymsp->TOP__ether_simulation__clt_inst__u_tcp__TCP_tx.__PVT__CLK;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__clt_inst__u_tcp__TCP_tx____PVT__nRST__0 
        = vlSymsp->TOP__ether_simulation__clt_inst__u_tcp__TCP_tx.__PVT__nRST;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__svr_inst__u_tcp__tcp_rcv____PVT__CLK__0 
        = vlSymsp->TOP__ether_simulation__svr_inst__u_tcp__tcp_rcv.__PVT__CLK;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__svr_inst__u_tcp__tcp_rcv____PVT__nRST__0 
        = vlSymsp->TOP__ether_simulation__svr_inst__u_tcp__tcp_rcv.__PVT__nRST;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__clt_inst__u_tcp__tcp_rcv____PVT__CLK__0 
        = vlSymsp->TOP__ether_simulation__clt_inst__u_tcp__tcp_rcv.__PVT__CLK;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__clt_inst__u_tcp__tcp_rcv____PVT__nRST__0 
        = vlSymsp->TOP__ether_simulation__clt_inst__u_tcp__tcp_rcv.__PVT__nRST;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__svr_inst__u_tcp__tcp_flow____PVT__CLK__0 
        = vlSymsp->TOP__ether_simulation__svr_inst__u_tcp__tcp_flow.__PVT__CLK;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__svr_inst__u_tcp__tcp_flow____PVT__nRST__0 
        = vlSymsp->TOP__ether_simulation__svr_inst__u_tcp__tcp_flow.__PVT__nRST;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__clt_inst__u_tcp__tcp_flow____PVT__CLK__0 
        = vlSymsp->TOP__ether_simulation__clt_inst__u_tcp__tcp_flow.__PVT__CLK;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__clt_inst__u_tcp__tcp_flow____PVT__nRST__0 
        = vlSymsp->TOP__ether_simulation__clt_inst__u_tcp__tcp_flow.__PVT__nRST;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__svr_inst__mac_rx__CRC____PVT__CLK__0 
        = vlSymsp->TOP__ether_simulation__svr_inst__mac_rx__CRC.__PVT__CLK;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__svr_inst__mac_rx__CRC____PVT__nRST__0 
        = vlSymsp->TOP__ether_simulation__svr_inst__mac_rx__CRC.__PVT__nRST;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__svr_inst__mac_tx__CRC____PVT__CLK__0 
        = vlSymsp->TOP__ether_simulation__svr_inst__mac_tx__CRC.__PVT__CLK;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__svr_inst__mac_tx__CRC____PVT__nRST__0 
        = vlSymsp->TOP__ether_simulation__svr_inst__mac_tx__CRC.__PVT__nRST;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__clt_inst__mac_rx__CRC____PVT__CLK__0 
        = vlSymsp->TOP__ether_simulation__clt_inst__mac_rx__CRC.__PVT__CLK;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__clt_inst__mac_rx__CRC____PVT__nRST__0 
        = vlSymsp->TOP__ether_simulation__clt_inst__mac_rx__CRC.__PVT__nRST;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__clt_inst__mac_tx__CRC____PVT__CLK__0 
        = vlSymsp->TOP__ether_simulation__clt_inst__mac_tx__CRC.__PVT__CLK;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__clt_inst__mac_tx__CRC____PVT__nRST__0 
        = vlSymsp->TOP__ether_simulation__clt_inst__mac_tx__CRC.__PVT__nRST;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__svr_inst__ip_rx__chksum_inst____PVT__CLK__0 
        = vlSymsp->TOP__ether_simulation__svr_inst__ip_rx__chksum_inst.__PVT__CLK;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__svr_inst__ip_rx__chksum_inst____PVT__nRST__0 
        = vlSymsp->TOP__ether_simulation__svr_inst__ip_rx__chksum_inst.__PVT__nRST;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__clt_inst__ip_rx__chksum_inst____PVT__CLK__0 
        = vlSymsp->TOP__ether_simulation__clt_inst__ip_rx__chksum_inst.__PVT__CLK;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__clt_inst__ip_rx__chksum_inst____PVT__nRST__0 
        = vlSymsp->TOP__ether_simulation__clt_inst__ip_rx__chksum_inst.__PVT__nRST;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__svr_inst__u_tcp__ISN_gen____PVT__CLK__0 
        = vlSymsp->TOP__ether_simulation__svr_inst__u_tcp__ISN_gen.__PVT__CLK;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__svr_inst__u_tcp__ISN_gen____PVT__nRST__0 
        = vlSymsp->TOP__ether_simulation__svr_inst__u_tcp__ISN_gen.__PVT__nRST;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__clt_inst__u_tcp__ISN_gen____PVT__CLK__0 
        = vlSymsp->TOP__ether_simulation__clt_inst__u_tcp__ISN_gen.__PVT__CLK;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__clt_inst__u_tcp__ISN_gen____PVT__nRST__0 
        = vlSymsp->TOP__ether_simulation__clt_inst__u_tcp__ISN_gen.__PVT__nRST;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__svr_inst__u_tcp__timeout_fl____PVT__CLK__0 
        = vlSymsp->TOP__ether_simulation__svr_inst__u_tcp__timeout_fl.__PVT__CLK;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__svr_inst__u_tcp__timeout_fl____PVT__nRST__0 
        = vlSymsp->TOP__ether_simulation__svr_inst__u_tcp__timeout_fl.__PVT__nRST;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__clt_inst__u_tcp__timeout_fl____PVT__CLK__0 
        = vlSymsp->TOP__ether_simulation__clt_inst__u_tcp__timeout_fl.__PVT__CLK;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__clt_inst__u_tcp__timeout_fl____PVT__nRST__0 
        = vlSymsp->TOP__ether_simulation__clt_inst__u_tcp__timeout_fl.__PVT__nRST;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__svr_inst__u_tcp__tcp_flow__timewait____PVT__CLK__0 
        = vlSymsp->TOP__ether_simulation__svr_inst__u_tcp__tcp_flow__timewait.__PVT__CLK;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__svr_inst__u_tcp__tcp_flow__timewait____PVT__nRST__0 
        = vlSymsp->TOP__ether_simulation__svr_inst__u_tcp__tcp_flow__timewait.__PVT__nRST;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__clt_inst__u_tcp__tcp_flow__timewait____PVT__CLK__0 
        = vlSymsp->TOP__ether_simulation__clt_inst__u_tcp__tcp_flow__timewait.__PVT__CLK;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__clt_inst__u_tcp__tcp_flow__timewait____PVT__nRST__0 
        = vlSymsp->TOP__ether_simulation__clt_inst__u_tcp__tcp_flow__timewait.__PVT__nRST;
}

VL_ATTR_COLD void Vether_simulation_ether_simulation___eval_initial__TOP__ether_simulation(Vether_simulation_ether_simulation* vlSelf);
VL_ATTR_COLD void Vether_simulation___024root____Vm_traceActivitySetAll(Vether_simulation___024root* vlSelf);
VL_ATTR_COLD void Vether_simulation_MAC_rx___eval_initial__TOP__ether_simulation__svr_inst__mac_rx(Vether_simulation_MAC_rx* vlSelf);
VL_ATTR_COLD void Vether_simulation_MAC_rx___eval_initial__TOP__ether_simulation__clt_inst__mac_rx(Vether_simulation_MAC_rx* vlSelf);
VL_ATTR_COLD void Vether_simulation_TCP__F10_CBz1___eval_initial__TOP__ether_simulation__svr_inst__u_tcp(Vether_simulation_TCP__F10_CBz1* vlSelf);
VL_ATTR_COLD void Vether_simulation_TCP__F10_CBz2___eval_initial__TOP__ether_simulation__clt_inst__u_tcp(Vether_simulation_TCP__F10_CBz2* vlSelf);
VL_ATTR_COLD void Vether_simulation_TCP_tx___eval_initial__TOP__ether_simulation__svr_inst__u_tcp__TCP_tx(Vether_simulation_TCP_tx* vlSelf);
VL_ATTR_COLD void Vether_simulation_TCP_tx___eval_initial__TOP__ether_simulation__clt_inst__u_tcp__TCP_tx(Vether_simulation_TCP_tx* vlSelf);
VL_ATTR_COLD void Vether_simulation_TCP_flow_ctrl___eval_initial__TOP__ether_simulation__svr_inst__u_tcp__tcp_flow(Vether_simulation_TCP_flow_ctrl* vlSelf);
VL_ATTR_COLD void Vether_simulation_TCP_flow_ctrl___eval_initial__TOP__ether_simulation__clt_inst__u_tcp__tcp_flow(Vether_simulation_TCP_flow_ctrl* vlSelf);

VL_ATTR_COLD void Vether_simulation___024root___eval_initial(Vether_simulation___024root* vlSelf) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vether_simulation___024root___eval_initial\n"); );
    Vether_simulation__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    Vether_simulation_ether_simulation___eval_initial__TOP__ether_simulation((&vlSymsp->TOP__ether_simulation));
    Vether_simulation___024root____Vm_traceActivitySetAll(vlSelf);
    Vether_simulation_MAC_rx___eval_initial__TOP__ether_simulation__svr_inst__mac_rx((&vlSymsp->TOP__ether_simulation__svr_inst__mac_rx));
    Vether_simulation_MAC_rx___eval_initial__TOP__ether_simulation__clt_inst__mac_rx((&vlSymsp->TOP__ether_simulation__clt_inst__mac_rx));
    Vether_simulation_TCP__F10_CBz1___eval_initial__TOP__ether_simulation__svr_inst__u_tcp((&vlSymsp->TOP__ether_simulation__svr_inst__u_tcp));
    Vether_simulation_TCP__F10_CBz2___eval_initial__TOP__ether_simulation__clt_inst__u_tcp((&vlSymsp->TOP__ether_simulation__clt_inst__u_tcp));
    Vether_simulation_TCP_tx___eval_initial__TOP__ether_simulation__svr_inst__u_tcp__TCP_tx((&vlSymsp->TOP__ether_simulation__svr_inst__u_tcp__TCP_tx));
    Vether_simulation_TCP_tx___eval_initial__TOP__ether_simulation__clt_inst__u_tcp__TCP_tx((&vlSymsp->TOP__ether_simulation__clt_inst__u_tcp__TCP_tx));
    Vether_simulation_TCP_flow_ctrl___eval_initial__TOP__ether_simulation__svr_inst__u_tcp__tcp_flow((&vlSymsp->TOP__ether_simulation__svr_inst__u_tcp__tcp_flow));
    Vether_simulation_TCP_flow_ctrl___eval_initial__TOP__ether_simulation__clt_inst__u_tcp__tcp_flow((&vlSymsp->TOP__ether_simulation__clt_inst__u_tcp__tcp_flow));
}

#ifdef VL_DEBUG
VL_ATTR_COLD void Vether_simulation___024root___dump_triggers__stl(Vether_simulation___024root* vlSelf);
#endif  // VL_DEBUG

VL_ATTR_COLD void Vether_simulation___024root___eval_triggers__stl(Vether_simulation___024root* vlSelf) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vether_simulation___024root___eval_triggers__stl\n"); );
    Vether_simulation__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    vlSelfRef.__VstlTriggered.setBit(0U, (IData)(vlSelfRef.__VstlFirstIteration));
    vlSelfRef.__VstlTriggered.setBit(1U, (vlSymsp->TOP__ether_simulation__svr_inst__mac_rx.__PVT__mac_dest_addr 
                                          != vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__svr_inst__mac_rx____PVT__mac_dest_addr__0));
    vlSelfRef.__VstlTriggered.setBit(2U, (vlSymsp->TOP__ether_simulation__clt_inst__mac_rx.__PVT__mac_dest_addr 
                                          != vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__clt_inst__mac_rx____PVT__mac_dest_addr__0));
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__svr_inst__mac_rx____PVT__mac_dest_addr__0 
        = vlSymsp->TOP__ether_simulation__svr_inst__mac_rx.__PVT__mac_dest_addr;
    vlSelfRef.__Vtrigprevexpr___TOP__ether_simulation__clt_inst__mac_rx____PVT__mac_dest_addr__0 
        = vlSymsp->TOP__ether_simulation__clt_inst__mac_rx.__PVT__mac_dest_addr;
    if (VL_UNLIKELY(((1U & (~ (IData)(vlSelfRef.__VstlDidInit)))))) {
        vlSelfRef.__VstlDidInit = 1U;
        vlSelfRef.__VstlTriggered.setBit(1U, 1U);
        vlSelfRef.__VstlTriggered.setBit(2U, 1U);
    }
#ifdef VL_DEBUG
    if (VL_UNLIKELY(vlSymsp->_vm_contextp__->debug())) {
        Vether_simulation___024root___dump_triggers__stl(vlSelf);
    }
#endif
}

VL_ATTR_COLD void Vether_simulation___024root___stl_sequent__TOP__0(Vether_simulation___024root* vlSelf);
VL_ATTR_COLD void Vether_simulation_top___stl_sequent__TOP__ether_simulation__clt_inst__0(Vether_simulation_top* vlSelf);
VL_ATTR_COLD void Vether_simulation_top__CBz1___stl_sequent__TOP__ether_simulation__svr_inst__0(Vether_simulation_top__CBz1* vlSelf);
VL_ATTR_COLD void Vether_simulation_MAC_rx___stl_sequent__TOP__ether_simulation__svr_inst__mac_rx__0(Vether_simulation_MAC_rx* vlSelf);
VL_ATTR_COLD void Vether_simulation_MAC_rx___stl_sequent__TOP__ether_simulation__clt_inst__mac_rx__0(Vether_simulation_MAC_rx* vlSelf);
VL_ATTR_COLD void Vether_simulation_TCP__F10_CBz1___stl_sequent__TOP__ether_simulation__svr_inst__u_tcp__0(Vether_simulation_TCP__F10_CBz1* vlSelf);
VL_ATTR_COLD void Vether_simulation_TCP__F10_CBz2___stl_sequent__TOP__ether_simulation__clt_inst__u_tcp__0(Vether_simulation_TCP__F10_CBz2* vlSelf);
VL_ATTR_COLD void Vether_simulation_xgmii_little_to_big___stl_sequent__TOP__ether_simulation__svr_inst__mac_rx__crc_convert__0(Vether_simulation_xgmii_little_to_big* vlSelf);
VL_ATTR_COLD void Vether_simulation_xgmii_little_to_big___stl_sequent__TOP__ether_simulation__svr_inst__mac_rx__crc_frame_convert__0(Vether_simulation_xgmii_little_to_big* vlSelf);
VL_ATTR_COLD void Vether_simulation_xgmii_little_to_big___stl_sequent__TOP__ether_simulation__svr_inst__mac_rx__payload_cvrt__0(Vether_simulation_xgmii_little_to_big* vlSelf);
VL_ATTR_COLD void Vether_simulation_xgmii_little_to_big___stl_sequent__TOP__ether_simulation__svr_inst__mac_rx__xgmii_cvrt__0(Vether_simulation_xgmii_little_to_big* vlSelf);
VL_ATTR_COLD void Vether_simulation_xgmii_little_to_big___stl_sequent__TOP__ether_simulation__clt_inst__mac_rx__crc_convert__0(Vether_simulation_xgmii_little_to_big* vlSelf);
VL_ATTR_COLD void Vether_simulation_xgmii_little_to_big___stl_sequent__TOP__ether_simulation__clt_inst__mac_rx__crc_frame_convert__0(Vether_simulation_xgmii_little_to_big* vlSelf);
VL_ATTR_COLD void Vether_simulation_xgmii_little_to_big___stl_sequent__TOP__ether_simulation__clt_inst__mac_rx__payload_cvrt__0(Vether_simulation_xgmii_little_to_big* vlSelf);
VL_ATTR_COLD void Vether_simulation_xgmii_little_to_big___stl_sequent__TOP__ether_simulation__clt_inst__mac_rx__xgmii_cvrt__0(Vether_simulation_xgmii_little_to_big* vlSelf);
VL_ATTR_COLD void Vether_simulation_payload_FIFO___stl_sequent__TOP__ether_simulation__svr_inst__u_payload_fifo__0(Vether_simulation_payload_FIFO* vlSelf);
VL_ATTR_COLD void Vether_simulation_payload_FIFO___stl_sequent__TOP__ether_simulation__clt_inst__u_payload_fifo__0(Vether_simulation_payload_FIFO* vlSelf);
VL_ATTR_COLD void Vether_simulation_FIFO_TX__F10___stl_sequent__TOP__ether_simulation__svr_inst__u_fifo_tx__0(Vether_simulation_FIFO_TX__F10* vlSelf);
VL_ATTR_COLD void Vether_simulation_FIFO_TX__F10___stl_sequent__TOP__ether_simulation__clt_inst__u_fifo_tx__0(Vether_simulation_FIFO_TX__F10* vlSelf);
VL_ATTR_COLD void Vether_simulation_TCP_flow_ctrl___stl_sequent__TOP__ether_simulation__svr_inst__u_tcp__tcp_flow__0(Vether_simulation_TCP_flow_ctrl* vlSelf);
VL_ATTR_COLD void Vether_simulation_TCP_flow_ctrl___stl_sequent__TOP__ether_simulation__clt_inst__u_tcp__tcp_flow__0(Vether_simulation_TCP_flow_ctrl* vlSelf);
VL_ATTR_COLD void Vether_simulation_crc32_parallel_64bit___stl_sequent__TOP__ether_simulation__svr_inst__mac_tx__CRC__0(Vether_simulation_crc32_parallel_64bit* vlSelf);
VL_ATTR_COLD void Vether_simulation_crc32_parallel_64bit___stl_sequent__TOP__ether_simulation__clt_inst__mac_tx__CRC__0(Vether_simulation_crc32_parallel_64bit* vlSelf);
VL_ATTR_COLD void Vether_simulation_chksum_tcp_pl___stl_sequent__TOP__ether_simulation__svr_inst__ip_rx__chksum_inst__0(Vether_simulation_chksum_tcp_pl* vlSelf);
VL_ATTR_COLD void Vether_simulation_chksum_tcp_pl___stl_sequent__TOP__ether_simulation__clt_inst__ip_rx__chksum_inst__0(Vether_simulation_chksum_tcp_pl* vlSelf);
VL_ATTR_COLD void Vether_simulation_crc32_parallel_64bit___stl_sequent__TOP__ether_simulation__svr_inst__mac_rx__CRC__0(Vether_simulation_crc32_parallel_64bit* vlSelf);
VL_ATTR_COLD void Vether_simulation_crc32_parallel_64bit___stl_sequent__TOP__ether_simulation__clt_inst__mac_rx__CRC__0(Vether_simulation_crc32_parallel_64bit* vlSelf);
VL_ATTR_COLD void Vether_simulation_MAC_tx___stl_sequent__TOP__ether_simulation__svr_inst__mac_tx__0(Vether_simulation_MAC_tx* vlSelf);
VL_ATTR_COLD void Vether_simulation_MAC_tx___stl_sequent__TOP__ether_simulation__clt_inst__mac_tx__0(Vether_simulation_MAC_tx* vlSelf);
VL_ATTR_COLD void Vether_simulation_ether_simulation___stl_sequent__TOP__ether_simulation__0(Vether_simulation_ether_simulation* vlSelf);
VL_ATTR_COLD void Vether_simulation_top__CBz1___stl_sequent__TOP__ether_simulation__svr_inst__1(Vether_simulation_top__CBz1* vlSelf);
VL_ATTR_COLD void Vether_simulation_top___stl_sequent__TOP__ether_simulation__clt_inst__1(Vether_simulation_top* vlSelf);
VL_ATTR_COLD void Vether_simulation_TCP_receiver___stl_sequent__TOP__ether_simulation__svr_inst__u_tcp__tcp_rcv__0(Vether_simulation_TCP_receiver* vlSelf);
VL_ATTR_COLD void Vether_simulation_flex_counter__S20___stl_sequent__TOP__ether_simulation__svr_inst__u_tcp__timeout_fl__0(Vether_simulation_flex_counter__S20* vlSelf);
VL_ATTR_COLD void Vether_simulation_TCP_receiver___stl_sequent__TOP__ether_simulation__clt_inst__u_tcp__tcp_rcv__0(Vether_simulation_TCP_receiver* vlSelf);
VL_ATTR_COLD void Vether_simulation_flex_counter__S20___stl_sequent__TOP__ether_simulation__clt_inst__u_tcp__timeout_fl__0(Vether_simulation_flex_counter__S20* vlSelf);
VL_ATTR_COLD void Vether_simulation_MAC_rx___stl_sequent__TOP__ether_simulation__svr_inst__mac_rx__1(Vether_simulation_MAC_rx* vlSelf);
VL_ATTR_COLD void Vether_simulation_MAC_rx___stl_sequent__TOP__ether_simulation__clt_inst__mac_rx__1(Vether_simulation_MAC_rx* vlSelf);
VL_ATTR_COLD void Vether_simulation_TCP__F10_CBz1___stl_sequent__TOP__ether_simulation__svr_inst__u_tcp__1(Vether_simulation_TCP__F10_CBz1* vlSelf);
VL_ATTR_COLD void Vether_simulation_priority_encoder__Wa___stl_sequent__TOP__ether_simulation__svr_inst__u_tcp__tcp_flow__me__0(Vether_simulation_priority_encoder__Wa* vlSelf);
VL_ATTR_COLD void Vether_simulation_priority_encoder__Wa___stl_sequent__TOP__ether_simulation__svr_inst__u_tcp__tcp_flow__lt__0(Vether_simulation_priority_encoder__Wa* vlSelf);
VL_ATTR_COLD void Vether_simulation_priority_encoder__Wa___stl_sequent__TOP__ether_simulation__svr_inst__u_tcp__tcp_flow__rt__0(Vether_simulation_priority_encoder__Wa* vlSelf);
VL_ATTR_COLD void Vether_simulation_priority_encoder__Wa___stl_sequent__TOP__ether_simulation__svr_inst__u_tcp__tcp_flow__ov__0(Vether_simulation_priority_encoder__Wa* vlSelf);
VL_ATTR_COLD void Vether_simulation_priority_encoder__Wa___stl_sequent__TOP__ether_simulation__svr_inst__u_tcp__tcp_flow__pe__0(Vether_simulation_priority_encoder__Wa* vlSelf);
VL_ATTR_COLD void Vether_simulation_TCP__F10_CBz2___stl_sequent__TOP__ether_simulation__clt_inst__u_tcp__1(Vether_simulation_TCP__F10_CBz2* vlSelf);
VL_ATTR_COLD void Vether_simulation_priority_encoder__Wa___stl_sequent__TOP__ether_simulation__clt_inst__u_tcp__tcp_flow__me__0(Vether_simulation_priority_encoder__Wa* vlSelf);
VL_ATTR_COLD void Vether_simulation_priority_encoder__Wa___stl_sequent__TOP__ether_simulation__clt_inst__u_tcp__tcp_flow__lt__0(Vether_simulation_priority_encoder__Wa* vlSelf);
VL_ATTR_COLD void Vether_simulation_priority_encoder__Wa___stl_sequent__TOP__ether_simulation__clt_inst__u_tcp__tcp_flow__rt__0(Vether_simulation_priority_encoder__Wa* vlSelf);
VL_ATTR_COLD void Vether_simulation_priority_encoder__Wa___stl_sequent__TOP__ether_simulation__clt_inst__u_tcp__tcp_flow__ov__0(Vether_simulation_priority_encoder__Wa* vlSelf);
VL_ATTR_COLD void Vether_simulation_priority_encoder__Wa___stl_sequent__TOP__ether_simulation__clt_inst__u_tcp__tcp_flow__pe__0(Vether_simulation_priority_encoder__Wa* vlSelf);
VL_ATTR_COLD void Vether_simulation_IP_rx___stl_sequent__TOP__ether_simulation__svr_inst__ip_rx__0(Vether_simulation_IP_rx* vlSelf);
VL_ATTR_COLD void Vether_simulation_IP_rx___stl_sequent__TOP__ether_simulation__clt_inst__ip_rx__0(Vether_simulation_IP_rx* vlSelf);
VL_ATTR_COLD void Vether_simulation___024root___stl_sequent__TOP__1(Vether_simulation___024root* vlSelf);
VL_ATTR_COLD void Vether_simulation_ether_simulation___stl_sequent__TOP__ether_simulation__1(Vether_simulation_ether_simulation* vlSelf);
VL_ATTR_COLD void Vether_simulation_MAC_tx___stl_sequent__TOP__ether_simulation__svr_inst__mac_tx__1(Vether_simulation_MAC_tx* vlSelf);
VL_ATTR_COLD void Vether_simulation_IP_tx___stl_sequent__TOP__ether_simulation__svr_inst__ip_tx__0(Vether_simulation_IP_tx* vlSelf);
VL_ATTR_COLD void Vether_simulation_MAC_tx___stl_sequent__TOP__ether_simulation__clt_inst__mac_tx__1(Vether_simulation_MAC_tx* vlSelf);
VL_ATTR_COLD void Vether_simulation_IP_tx___stl_sequent__TOP__ether_simulation__clt_inst__ip_tx__0(Vether_simulation_IP_tx* vlSelf);
VL_ATTR_COLD void Vether_simulation_top__CBz1___stl_sequent__TOP__ether_simulation__svr_inst__2(Vether_simulation_top__CBz1* vlSelf);
VL_ATTR_COLD void Vether_simulation_top___stl_sequent__TOP__ether_simulation__clt_inst__2(Vether_simulation_top* vlSelf);
VL_ATTR_COLD void Vether_simulation_TCP_flow_ctrl___stl_sequent__TOP__ether_simulation__svr_inst__u_tcp__tcp_flow__1(Vether_simulation_TCP_flow_ctrl* vlSelf);
VL_ATTR_COLD void Vether_simulation_checksum_TCP___stl_sequent__TOP__ether_simulation__svr_inst__u_tcp__inst__0(Vether_simulation_checksum_TCP* vlSelf);
VL_ATTR_COLD void Vether_simulation_TCP_flow_ctrl___stl_sequent__TOP__ether_simulation__clt_inst__u_tcp__tcp_flow__1(Vether_simulation_TCP_flow_ctrl* vlSelf);
VL_ATTR_COLD void Vether_simulation_checksum_TCP___stl_sequent__TOP__ether_simulation__clt_inst__u_tcp__inst__0(Vether_simulation_checksum_TCP* vlSelf);
VL_ATTR_COLD void Vether_simulation___024root___stl_sequent__TOP__2(Vether_simulation___024root* vlSelf);
VL_ATTR_COLD void Vether_simulation_xgmii_little_to_big___stl_sequent__TOP__ether_simulation__cvrt_svr__0(Vether_simulation_xgmii_little_to_big* vlSelf);
VL_ATTR_COLD void Vether_simulation_xgmii_little_to_big___stl_sequent__TOP__ether_simulation__cvrt_clt__0(Vether_simulation_xgmii_little_to_big* vlSelf);
VL_ATTR_COLD void Vether_simulation_crc32_parallel_64bit___stl_sequent__TOP__ether_simulation__svr_inst__mac_tx__CRC__1(Vether_simulation_crc32_parallel_64bit* vlSelf);
VL_ATTR_COLD void Vether_simulation_crc32_parallel_64bit___stl_sequent__TOP__ether_simulation__clt_inst__mac_tx__CRC__1(Vether_simulation_crc32_parallel_64bit* vlSelf);
VL_ATTR_COLD void Vether_simulation_ether_simulation___stl_sequent__TOP__ether_simulation__2(Vether_simulation_ether_simulation* vlSelf);
VL_ATTR_COLD void Vether_simulation_IP_rx___stl_sequent__TOP__ether_simulation__svr_inst__ip_rx__1(Vether_simulation_IP_rx* vlSelf);
VL_ATTR_COLD void Vether_simulation_TCP__F10_CBz1___stl_sequent__TOP__ether_simulation__svr_inst__u_tcp__2(Vether_simulation_TCP__F10_CBz1* vlSelf);
VL_ATTR_COLD void Vether_simulation_IP_rx___stl_sequent__TOP__ether_simulation__clt_inst__ip_rx__1(Vether_simulation_IP_rx* vlSelf);
VL_ATTR_COLD void Vether_simulation_TCP__F10_CBz2___stl_sequent__TOP__ether_simulation__clt_inst__u_tcp__2(Vether_simulation_TCP__F10_CBz2* vlSelf);
VL_ATTR_COLD void Vether_simulation_flex_counter__S9___stl_sequent__TOP__ether_simulation__svr_inst__u_tcp__tcp_flow__timewait__0(Vether_simulation_flex_counter__S9* vlSelf);
VL_ATTR_COLD void Vether_simulation_flex_counter__S9___stl_sequent__TOP__ether_simulation__clt_inst__u_tcp__tcp_flow__timewait__0(Vether_simulation_flex_counter__S9* vlSelf);
VL_ATTR_COLD void Vether_simulation___024root___stl_sequent__TOP__3(Vether_simulation___024root* vlSelf);
VL_ATTR_COLD void Vether_simulation_top___stl_sequent__TOP__ether_simulation__clt_inst__3(Vether_simulation_top* vlSelf);
VL_ATTR_COLD void Vether_simulation_top__CBz1___stl_sequent__TOP__ether_simulation__svr_inst__3(Vether_simulation_top__CBz1* vlSelf);
VL_ATTR_COLD void Vether_simulation_chksum_tcp_pl___stl_sequent__TOP__ether_simulation__svr_inst__ip_rx__chksum_inst__1(Vether_simulation_chksum_tcp_pl* vlSelf);
VL_ATTR_COLD void Vether_simulation_TCP_tx___stl_sequent__TOP__ether_simulation__svr_inst__u_tcp__TCP_tx__0(Vether_simulation_TCP_tx* vlSelf);
VL_ATTR_COLD void Vether_simulation_chksum_tcp_pl___stl_sequent__TOP__ether_simulation__clt_inst__ip_rx__chksum_inst__1(Vether_simulation_chksum_tcp_pl* vlSelf);
VL_ATTR_COLD void Vether_simulation_TCP_tx___stl_sequent__TOP__ether_simulation__clt_inst__u_tcp__TCP_tx__0(Vether_simulation_TCP_tx* vlSelf);
VL_ATTR_COLD void Vether_simulation_MAC_rx___stl_sequent__TOP__ether_simulation__clt_inst__mac_rx__2(Vether_simulation_MAC_rx* vlSelf);
VL_ATTR_COLD void Vether_simulation_TCP__F10_CBz2___stl_sequent__TOP__ether_simulation__clt_inst__u_tcp__3(Vether_simulation_TCP__F10_CBz2* vlSelf);
VL_ATTR_COLD void Vether_simulation_ether_simulation___stl_sequent__TOP__ether_simulation__3(Vether_simulation_ether_simulation* vlSelf);
VL_ATTR_COLD void Vether_simulation_payload_FIFO___stl_sequent__TOP__ether_simulation__clt_inst__u_payload_fifo__1(Vether_simulation_payload_FIFO* vlSelf);
VL_ATTR_COLD void Vether_simulation_MAC_rx___stl_sequent__TOP__ether_simulation__svr_inst__mac_rx__2(Vether_simulation_MAC_rx* vlSelf);
VL_ATTR_COLD void Vether_simulation_TCP__F10_CBz1___stl_sequent__TOP__ether_simulation__svr_inst__u_tcp__3(Vether_simulation_TCP__F10_CBz1* vlSelf);
VL_ATTR_COLD void Vether_simulation_payload_FIFO___stl_sequent__TOP__ether_simulation__svr_inst__u_payload_fifo__1(Vether_simulation_payload_FIFO* vlSelf);
VL_ATTR_COLD void Vether_simulation_priority_encoder__W8_Mz2___stl_sequent__TOP__ether_simulation__clt_inst__mac_rx__crc_check_encoder__0(Vether_simulation_priority_encoder__W8_Mz2* vlSelf);
VL_ATTR_COLD void Vether_simulation_priority_encoder__W10_Mz2___stl_sequent__TOP__ether_simulation__clt_inst__mac_rx__xgmii_fcs__0(Vether_simulation_priority_encoder__W10_Mz2* vlSelf);
VL_ATTR_COLD void Vether_simulation_top___stl_sequent__TOP__ether_simulation__clt_inst__4(Vether_simulation_top* vlSelf);
VL_ATTR_COLD void Vether_simulation___024root___stl_sequent__TOP__4(Vether_simulation___024root* vlSelf);
VL_ATTR_COLD void Vether_simulation_priority_encoder__W8_Mz2___stl_sequent__TOP__ether_simulation__svr_inst__mac_rx__crc_check_encoder__0(Vether_simulation_priority_encoder__W8_Mz2* vlSelf);
VL_ATTR_COLD void Vether_simulation_priority_encoder__W10_Mz2___stl_sequent__TOP__ether_simulation__svr_inst__mac_rx__xgmii_fcs__0(Vether_simulation_priority_encoder__W10_Mz2* vlSelf);
VL_ATTR_COLD void Vether_simulation_top__CBz1___stl_sequent__TOP__ether_simulation__svr_inst__4(Vether_simulation_top__CBz1* vlSelf);
VL_ATTR_COLD void Vether_simulation_MAC_rx___stl_sequent__TOP__ether_simulation__clt_inst__mac_rx__3(Vether_simulation_MAC_rx* vlSelf);
VL_ATTR_COLD void Vether_simulation_FIFO_TX__F10___stl_sequent__TOP__ether_simulation__clt_inst__u_fifo_tx__1(Vether_simulation_FIFO_TX__F10* vlSelf);
VL_ATTR_COLD void Vether_simulation_MAC_rx___stl_sequent__TOP__ether_simulation__svr_inst__mac_rx__3(Vether_simulation_MAC_rx* vlSelf);
VL_ATTR_COLD void Vether_simulation_FIFO_TX__F10___stl_sequent__TOP__ether_simulation__svr_inst__u_fifo_tx__1(Vether_simulation_FIFO_TX__F10* vlSelf);
VL_ATTR_COLD void Vether_simulation_MAC_rx___stl_comb__TOP__ether_simulation__clt_inst__mac_rx__0(Vether_simulation_MAC_rx* vlSelf);
VL_ATTR_COLD void Vether_simulation_top___stl_comb__TOP__ether_simulation__clt_inst__0(Vether_simulation_top* vlSelf);
VL_ATTR_COLD void Vether_simulation_xgmii_little_to_big___stl_comb__TOP__ether_simulation__clt_inst__mac_rx__xgmii_cvrt__0(Vether_simulation_xgmii_little_to_big* vlSelf);
VL_ATTR_COLD void Vether_simulation_xgmii_little_to_big___stl_comb__TOP__ether_simulation__clt_inst__mac_rx__crc_convert__0(Vether_simulation_xgmii_little_to_big* vlSelf);
VL_ATTR_COLD void Vether_simulation_MAC_rx___stl_comb__TOP__ether_simulation__clt_inst__mac_rx__1(Vether_simulation_MAC_rx* vlSelf);
VL_ATTR_COLD void Vether_simulation_crc32_parallel_64bit___stl_comb__TOP__ether_simulation__clt_inst__mac_rx__CRC__0(Vether_simulation_crc32_parallel_64bit* vlSelf);
VL_ATTR_COLD void Vether_simulation_MAC_rx___stl_comb__TOP__ether_simulation__svr_inst__mac_rx__0(Vether_simulation_MAC_rx* vlSelf);
VL_ATTR_COLD void Vether_simulation_top__CBz1___stl_comb__TOP__ether_simulation__svr_inst__0(Vether_simulation_top__CBz1* vlSelf);
VL_ATTR_COLD void Vether_simulation_xgmii_little_to_big___stl_comb__TOP__ether_simulation__svr_inst__mac_rx__xgmii_cvrt__0(Vether_simulation_xgmii_little_to_big* vlSelf);
VL_ATTR_COLD void Vether_simulation_xgmii_little_to_big___stl_comb__TOP__ether_simulation__svr_inst__mac_rx__crc_convert__0(Vether_simulation_xgmii_little_to_big* vlSelf);
VL_ATTR_COLD void Vether_simulation_MAC_rx___stl_comb__TOP__ether_simulation__svr_inst__mac_rx__1(Vether_simulation_MAC_rx* vlSelf);
VL_ATTR_COLD void Vether_simulation_crc32_parallel_64bit___stl_comb__TOP__ether_simulation__svr_inst__mac_rx__CRC__0(Vether_simulation_crc32_parallel_64bit* vlSelf);

VL_ATTR_COLD void Vether_simulation___024root___eval_stl(Vether_simulation___024root* vlSelf) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vether_simulation___024root___eval_stl\n"); );
    Vether_simulation__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    if ((1ULL & vlSelfRef.__VstlTriggered.word(0U))) {
        Vether_simulation___024root___stl_sequent__TOP__0(vlSelf);
        Vether_simulation___024root____Vm_traceActivitySetAll(vlSelf);
        Vether_simulation_top___stl_sequent__TOP__ether_simulation__clt_inst__0((&vlSymsp->TOP__ether_simulation__clt_inst));
        Vether_simulation_top__CBz1___stl_sequent__TOP__ether_simulation__svr_inst__0((&vlSymsp->TOP__ether_simulation__svr_inst));
        Vether_simulation_MAC_rx___stl_sequent__TOP__ether_simulation__svr_inst__mac_rx__0((&vlSymsp->TOP__ether_simulation__svr_inst__mac_rx));
        Vether_simulation_MAC_rx___stl_sequent__TOP__ether_simulation__clt_inst__mac_rx__0((&vlSymsp->TOP__ether_simulation__clt_inst__mac_rx));
        Vether_simulation_TCP__F10_CBz1___stl_sequent__TOP__ether_simulation__svr_inst__u_tcp__0((&vlSymsp->TOP__ether_simulation__svr_inst__u_tcp));
        Vether_simulation_TCP__F10_CBz2___stl_sequent__TOP__ether_simulation__clt_inst__u_tcp__0((&vlSymsp->TOP__ether_simulation__clt_inst__u_tcp));
        Vether_simulation_xgmii_little_to_big___stl_sequent__TOP__ether_simulation__svr_inst__mac_rx__crc_convert__0((&vlSymsp->TOP__ether_simulation__svr_inst__mac_rx__crc_convert));
        Vether_simulation_xgmii_little_to_big___stl_sequent__TOP__ether_simulation__svr_inst__mac_rx__crc_frame_convert__0((&vlSymsp->TOP__ether_simulation__svr_inst__mac_rx__crc_frame_convert));
        Vether_simulation_xgmii_little_to_big___stl_sequent__TOP__ether_simulation__svr_inst__mac_rx__payload_cvrt__0((&vlSymsp->TOP__ether_simulation__svr_inst__mac_rx__payload_cvrt));
        Vether_simulation_xgmii_little_to_big___stl_sequent__TOP__ether_simulation__svr_inst__mac_rx__xgmii_cvrt__0((&vlSymsp->TOP__ether_simulation__svr_inst__mac_rx__xgmii_cvrt));
        Vether_simulation_xgmii_little_to_big___stl_sequent__TOP__ether_simulation__clt_inst__mac_rx__crc_convert__0((&vlSymsp->TOP__ether_simulation__clt_inst__mac_rx__crc_convert));
        Vether_simulation_xgmii_little_to_big___stl_sequent__TOP__ether_simulation__clt_inst__mac_rx__crc_frame_convert__0((&vlSymsp->TOP__ether_simulation__clt_inst__mac_rx__crc_frame_convert));
        Vether_simulation_xgmii_little_to_big___stl_sequent__TOP__ether_simulation__clt_inst__mac_rx__payload_cvrt__0((&vlSymsp->TOP__ether_simulation__clt_inst__mac_rx__payload_cvrt));
        Vether_simulation_xgmii_little_to_big___stl_sequent__TOP__ether_simulation__clt_inst__mac_rx__xgmii_cvrt__0((&vlSymsp->TOP__ether_simulation__clt_inst__mac_rx__xgmii_cvrt));
        Vether_simulation_payload_FIFO___stl_sequent__TOP__ether_simulation__svr_inst__u_payload_fifo__0((&vlSymsp->TOP__ether_simulation__svr_inst__u_payload_fifo));
        Vether_simulation_payload_FIFO___stl_sequent__TOP__ether_simulation__clt_inst__u_payload_fifo__0((&vlSymsp->TOP__ether_simulation__clt_inst__u_payload_fifo));
        Vether_simulation_FIFO_TX__F10___stl_sequent__TOP__ether_simulation__svr_inst__u_fifo_tx__0((&vlSymsp->TOP__ether_simulation__svr_inst__u_fifo_tx));
        Vether_simulation_FIFO_TX__F10___stl_sequent__TOP__ether_simulation__clt_inst__u_fifo_tx__0((&vlSymsp->TOP__ether_simulation__clt_inst__u_fifo_tx));
        Vether_simulation_TCP_flow_ctrl___stl_sequent__TOP__ether_simulation__svr_inst__u_tcp__tcp_flow__0((&vlSymsp->TOP__ether_simulation__svr_inst__u_tcp__tcp_flow));
        Vether_simulation_TCP_flow_ctrl___stl_sequent__TOP__ether_simulation__clt_inst__u_tcp__tcp_flow__0((&vlSymsp->TOP__ether_simulation__clt_inst__u_tcp__tcp_flow));
        Vether_simulation_crc32_parallel_64bit___stl_sequent__TOP__ether_simulation__svr_inst__mac_tx__CRC__0((&vlSymsp->TOP__ether_simulation__svr_inst__mac_tx__CRC));
        Vether_simulation_crc32_parallel_64bit___stl_sequent__TOP__ether_simulation__clt_inst__mac_tx__CRC__0((&vlSymsp->TOP__ether_simulation__clt_inst__mac_tx__CRC));
        Vether_simulation_chksum_tcp_pl___stl_sequent__TOP__ether_simulation__svr_inst__ip_rx__chksum_inst__0((&vlSymsp->TOP__ether_simulation__svr_inst__ip_rx__chksum_inst));
        Vether_simulation_chksum_tcp_pl___stl_sequent__TOP__ether_simulation__clt_inst__ip_rx__chksum_inst__0((&vlSymsp->TOP__ether_simulation__clt_inst__ip_rx__chksum_inst));
        Vether_simulation_crc32_parallel_64bit___stl_sequent__TOP__ether_simulation__svr_inst__mac_rx__CRC__0((&vlSymsp->TOP__ether_simulation__svr_inst__mac_rx__CRC));
        Vether_simulation_crc32_parallel_64bit___stl_sequent__TOP__ether_simulation__clt_inst__mac_rx__CRC__0((&vlSymsp->TOP__ether_simulation__clt_inst__mac_rx__CRC));
        Vether_simulation_MAC_tx___stl_sequent__TOP__ether_simulation__svr_inst__mac_tx__0((&vlSymsp->TOP__ether_simulation__svr_inst__mac_tx));
        Vether_simulation_MAC_tx___stl_sequent__TOP__ether_simulation__clt_inst__mac_tx__0((&vlSymsp->TOP__ether_simulation__clt_inst__mac_tx));
        Vether_simulation_ether_simulation___stl_sequent__TOP__ether_simulation__0((&vlSymsp->TOP__ether_simulation));
        Vether_simulation_top__CBz1___stl_sequent__TOP__ether_simulation__svr_inst__1((&vlSymsp->TOP__ether_simulation__svr_inst));
        Vether_simulation_top___stl_sequent__TOP__ether_simulation__clt_inst__1((&vlSymsp->TOP__ether_simulation__clt_inst));
        Vether_simulation_TCP_receiver___stl_sequent__TOP__ether_simulation__svr_inst__u_tcp__tcp_rcv__0((&vlSymsp->TOP__ether_simulation__svr_inst__u_tcp__tcp_rcv));
        Vether_simulation_flex_counter__S20___stl_sequent__TOP__ether_simulation__svr_inst__u_tcp__timeout_fl__0((&vlSymsp->TOP__ether_simulation__svr_inst__u_tcp__timeout_fl));
        Vether_simulation_TCP_receiver___stl_sequent__TOP__ether_simulation__clt_inst__u_tcp__tcp_rcv__0((&vlSymsp->TOP__ether_simulation__clt_inst__u_tcp__tcp_rcv));
        Vether_simulation_flex_counter__S20___stl_sequent__TOP__ether_simulation__clt_inst__u_tcp__timeout_fl__0((&vlSymsp->TOP__ether_simulation__clt_inst__u_tcp__timeout_fl));
        Vether_simulation_MAC_rx___stl_sequent__TOP__ether_simulation__svr_inst__mac_rx__1((&vlSymsp->TOP__ether_simulation__svr_inst__mac_rx));
        Vether_simulation_MAC_rx___stl_sequent__TOP__ether_simulation__clt_inst__mac_rx__1((&vlSymsp->TOP__ether_simulation__clt_inst__mac_rx));
        Vether_simulation_TCP__F10_CBz1___stl_sequent__TOP__ether_simulation__svr_inst__u_tcp__1((&vlSymsp->TOP__ether_simulation__svr_inst__u_tcp));
        Vether_simulation_priority_encoder__Wa___stl_sequent__TOP__ether_simulation__svr_inst__u_tcp__tcp_flow__me__0((&vlSymsp->TOP__ether_simulation__svr_inst__u_tcp__tcp_flow__me));
        Vether_simulation_priority_encoder__Wa___stl_sequent__TOP__ether_simulation__svr_inst__u_tcp__tcp_flow__lt__0((&vlSymsp->TOP__ether_simulation__svr_inst__u_tcp__tcp_flow__lt));
        Vether_simulation_priority_encoder__Wa___stl_sequent__TOP__ether_simulation__svr_inst__u_tcp__tcp_flow__rt__0((&vlSymsp->TOP__ether_simulation__svr_inst__u_tcp__tcp_flow__rt));
        Vether_simulation_priority_encoder__Wa___stl_sequent__TOP__ether_simulation__svr_inst__u_tcp__tcp_flow__ov__0((&vlSymsp->TOP__ether_simulation__svr_inst__u_tcp__tcp_flow__ov));
        Vether_simulation_priority_encoder__Wa___stl_sequent__TOP__ether_simulation__svr_inst__u_tcp__tcp_flow__pe__0((&vlSymsp->TOP__ether_simulation__svr_inst__u_tcp__tcp_flow__pe));
        Vether_simulation_TCP__F10_CBz2___stl_sequent__TOP__ether_simulation__clt_inst__u_tcp__1((&vlSymsp->TOP__ether_simulation__clt_inst__u_tcp));
        Vether_simulation_priority_encoder__Wa___stl_sequent__TOP__ether_simulation__clt_inst__u_tcp__tcp_flow__me__0((&vlSymsp->TOP__ether_simulation__clt_inst__u_tcp__tcp_flow__me));
        Vether_simulation_priority_encoder__Wa___stl_sequent__TOP__ether_simulation__clt_inst__u_tcp__tcp_flow__lt__0((&vlSymsp->TOP__ether_simulation__clt_inst__u_tcp__tcp_flow__lt));
        Vether_simulation_priority_encoder__Wa___stl_sequent__TOP__ether_simulation__clt_inst__u_tcp__tcp_flow__rt__0((&vlSymsp->TOP__ether_simulation__clt_inst__u_tcp__tcp_flow__rt));
        Vether_simulation_priority_encoder__Wa___stl_sequent__TOP__ether_simulation__clt_inst__u_tcp__tcp_flow__ov__0((&vlSymsp->TOP__ether_simulation__clt_inst__u_tcp__tcp_flow__ov));
        Vether_simulation_priority_encoder__Wa___stl_sequent__TOP__ether_simulation__clt_inst__u_tcp__tcp_flow__pe__0((&vlSymsp->TOP__ether_simulation__clt_inst__u_tcp__tcp_flow__pe));
        Vether_simulation_IP_rx___stl_sequent__TOP__ether_simulation__svr_inst__ip_rx__0((&vlSymsp->TOP__ether_simulation__svr_inst__ip_rx));
        Vether_simulation_IP_rx___stl_sequent__TOP__ether_simulation__clt_inst__ip_rx__0((&vlSymsp->TOP__ether_simulation__clt_inst__ip_rx));
        Vether_simulation___024root___stl_sequent__TOP__1(vlSelf);
        Vether_simulation_ether_simulation___stl_sequent__TOP__ether_simulation__1((&vlSymsp->TOP__ether_simulation));
        Vether_simulation_MAC_tx___stl_sequent__TOP__ether_simulation__svr_inst__mac_tx__1((&vlSymsp->TOP__ether_simulation__svr_inst__mac_tx));
        Vether_simulation_IP_tx___stl_sequent__TOP__ether_simulation__svr_inst__ip_tx__0((&vlSymsp->TOP__ether_simulation__svr_inst__ip_tx));
        Vether_simulation_MAC_tx___stl_sequent__TOP__ether_simulation__clt_inst__mac_tx__1((&vlSymsp->TOP__ether_simulation__clt_inst__mac_tx));
        Vether_simulation_IP_tx___stl_sequent__TOP__ether_simulation__clt_inst__ip_tx__0((&vlSymsp->TOP__ether_simulation__clt_inst__ip_tx));
        Vether_simulation_top__CBz1___stl_sequent__TOP__ether_simulation__svr_inst__2((&vlSymsp->TOP__ether_simulation__svr_inst));
        Vether_simulation_top___stl_sequent__TOP__ether_simulation__clt_inst__2((&vlSymsp->TOP__ether_simulation__clt_inst));
        Vether_simulation_TCP_flow_ctrl___stl_sequent__TOP__ether_simulation__svr_inst__u_tcp__tcp_flow__1((&vlSymsp->TOP__ether_simulation__svr_inst__u_tcp__tcp_flow));
        Vether_simulation_checksum_TCP___stl_sequent__TOP__ether_simulation__svr_inst__u_tcp__inst__0((&vlSymsp->TOP__ether_simulation__svr_inst__u_tcp__inst));
        Vether_simulation_TCP_flow_ctrl___stl_sequent__TOP__ether_simulation__clt_inst__u_tcp__tcp_flow__1((&vlSymsp->TOP__ether_simulation__clt_inst__u_tcp__tcp_flow));
        Vether_simulation_checksum_TCP___stl_sequent__TOP__ether_simulation__clt_inst__u_tcp__inst__0((&vlSymsp->TOP__ether_simulation__clt_inst__u_tcp__inst));
        Vether_simulation___024root___stl_sequent__TOP__2(vlSelf);
        Vether_simulation_xgmii_little_to_big___stl_sequent__TOP__ether_simulation__cvrt_svr__0((&vlSymsp->TOP__ether_simulation__cvrt_svr));
        Vether_simulation_xgmii_little_to_big___stl_sequent__TOP__ether_simulation__cvrt_clt__0((&vlSymsp->TOP__ether_simulation__cvrt_clt));
        Vether_simulation_crc32_parallel_64bit___stl_sequent__TOP__ether_simulation__svr_inst__mac_tx__CRC__1((&vlSymsp->TOP__ether_simulation__svr_inst__mac_tx__CRC));
        Vether_simulation_crc32_parallel_64bit___stl_sequent__TOP__ether_simulation__clt_inst__mac_tx__CRC__1((&vlSymsp->TOP__ether_simulation__clt_inst__mac_tx__CRC));
        Vether_simulation_ether_simulation___stl_sequent__TOP__ether_simulation__2((&vlSymsp->TOP__ether_simulation));
        Vether_simulation_IP_rx___stl_sequent__TOP__ether_simulation__svr_inst__ip_rx__1((&vlSymsp->TOP__ether_simulation__svr_inst__ip_rx));
        Vether_simulation_TCP__F10_CBz1___stl_sequent__TOP__ether_simulation__svr_inst__u_tcp__2((&vlSymsp->TOP__ether_simulation__svr_inst__u_tcp));
        Vether_simulation_IP_rx___stl_sequent__TOP__ether_simulation__clt_inst__ip_rx__1((&vlSymsp->TOP__ether_simulation__clt_inst__ip_rx));
        Vether_simulation_TCP__F10_CBz2___stl_sequent__TOP__ether_simulation__clt_inst__u_tcp__2((&vlSymsp->TOP__ether_simulation__clt_inst__u_tcp));
        Vether_simulation_flex_counter__S9___stl_sequent__TOP__ether_simulation__svr_inst__u_tcp__tcp_flow__timewait__0((&vlSymsp->TOP__ether_simulation__svr_inst__u_tcp__tcp_flow__timewait));
        Vether_simulation_flex_counter__S9___stl_sequent__TOP__ether_simulation__clt_inst__u_tcp__tcp_flow__timewait__0((&vlSymsp->TOP__ether_simulation__clt_inst__u_tcp__tcp_flow__timewait));
        Vether_simulation___024root___stl_sequent__TOP__3(vlSelf);
        Vether_simulation_top___stl_sequent__TOP__ether_simulation__clt_inst__3((&vlSymsp->TOP__ether_simulation__clt_inst));
        Vether_simulation_top__CBz1___stl_sequent__TOP__ether_simulation__svr_inst__3((&vlSymsp->TOP__ether_simulation__svr_inst));
        Vether_simulation_chksum_tcp_pl___stl_sequent__TOP__ether_simulation__svr_inst__ip_rx__chksum_inst__1((&vlSymsp->TOP__ether_simulation__svr_inst__ip_rx__chksum_inst));
        Vether_simulation_TCP_tx___stl_sequent__TOP__ether_simulation__svr_inst__u_tcp__TCP_tx__0((&vlSymsp->TOP__ether_simulation__svr_inst__u_tcp__TCP_tx));
        Vether_simulation_chksum_tcp_pl___stl_sequent__TOP__ether_simulation__clt_inst__ip_rx__chksum_inst__1((&vlSymsp->TOP__ether_simulation__clt_inst__ip_rx__chksum_inst));
        Vether_simulation_TCP_tx___stl_sequent__TOP__ether_simulation__clt_inst__u_tcp__TCP_tx__0((&vlSymsp->TOP__ether_simulation__clt_inst__u_tcp__TCP_tx));
        Vether_simulation_MAC_rx___stl_sequent__TOP__ether_simulation__clt_inst__mac_rx__2((&vlSymsp->TOP__ether_simulation__clt_inst__mac_rx));
        Vether_simulation_TCP__F10_CBz2___stl_sequent__TOP__ether_simulation__clt_inst__u_tcp__3((&vlSymsp->TOP__ether_simulation__clt_inst__u_tcp));
        Vether_simulation_ether_simulation___stl_sequent__TOP__ether_simulation__3((&vlSymsp->TOP__ether_simulation));
        Vether_simulation_payload_FIFO___stl_sequent__TOP__ether_simulation__clt_inst__u_payload_fifo__1((&vlSymsp->TOP__ether_simulation__clt_inst__u_payload_fifo));
        Vether_simulation_MAC_rx___stl_sequent__TOP__ether_simulation__svr_inst__mac_rx__2((&vlSymsp->TOP__ether_simulation__svr_inst__mac_rx));
        Vether_simulation_TCP__F10_CBz1___stl_sequent__TOP__ether_simulation__svr_inst__u_tcp__3((&vlSymsp->TOP__ether_simulation__svr_inst__u_tcp));
        Vether_simulation_payload_FIFO___stl_sequent__TOP__ether_simulation__svr_inst__u_payload_fifo__1((&vlSymsp->TOP__ether_simulation__svr_inst__u_payload_fifo));
        Vether_simulation_priority_encoder__W8_Mz2___stl_sequent__TOP__ether_simulation__clt_inst__mac_rx__crc_check_encoder__0((&vlSymsp->TOP__ether_simulation__clt_inst__mac_rx__crc_check_encoder));
        Vether_simulation_priority_encoder__W10_Mz2___stl_sequent__TOP__ether_simulation__clt_inst__mac_rx__xgmii_fcs__0((&vlSymsp->TOP__ether_simulation__clt_inst__mac_rx__xgmii_fcs));
        Vether_simulation_top___stl_sequent__TOP__ether_simulation__clt_inst__4((&vlSymsp->TOP__ether_simulation__clt_inst));
        Vether_simulation___024root___stl_sequent__TOP__4(vlSelf);
        Vether_simulation_priority_encoder__W8_Mz2___stl_sequent__TOP__ether_simulation__svr_inst__mac_rx__crc_check_encoder__0((&vlSymsp->TOP__ether_simulation__svr_inst__mac_rx__crc_check_encoder));
        Vether_simulation_priority_encoder__W10_Mz2___stl_sequent__TOP__ether_simulation__svr_inst__mac_rx__xgmii_fcs__0((&vlSymsp->TOP__ether_simulation__svr_inst__mac_rx__xgmii_fcs));
        Vether_simulation_top__CBz1___stl_sequent__TOP__ether_simulation__svr_inst__4((&vlSymsp->TOP__ether_simulation__svr_inst));
        Vether_simulation_MAC_rx___stl_sequent__TOP__ether_simulation__clt_inst__mac_rx__3((&vlSymsp->TOP__ether_simulation__clt_inst__mac_rx));
        Vether_simulation_FIFO_TX__F10___stl_sequent__TOP__ether_simulation__clt_inst__u_fifo_tx__1((&vlSymsp->TOP__ether_simulation__clt_inst__u_fifo_tx));
        Vether_simulation_MAC_rx___stl_sequent__TOP__ether_simulation__svr_inst__mac_rx__3((&vlSymsp->TOP__ether_simulation__svr_inst__mac_rx));
        Vether_simulation_FIFO_TX__F10___stl_sequent__TOP__ether_simulation__svr_inst__u_fifo_tx__1((&vlSymsp->TOP__ether_simulation__svr_inst__u_fifo_tx));
    }
    if ((5ULL & vlSelfRef.__VstlTriggered.word(0U))) {
        Vether_simulation_MAC_rx___stl_comb__TOP__ether_simulation__clt_inst__mac_rx__0((&vlSymsp->TOP__ether_simulation__clt_inst__mac_rx));
        Vether_simulation___024root____Vm_traceActivitySetAll(vlSelf);
        Vether_simulation_top___stl_comb__TOP__ether_simulation__clt_inst__0((&vlSymsp->TOP__ether_simulation__clt_inst));
        Vether_simulation_xgmii_little_to_big___stl_comb__TOP__ether_simulation__clt_inst__mac_rx__xgmii_cvrt__0((&vlSymsp->TOP__ether_simulation__clt_inst__mac_rx__xgmii_cvrt));
        Vether_simulation_xgmii_little_to_big___stl_comb__TOP__ether_simulation__clt_inst__mac_rx__crc_convert__0((&vlSymsp->TOP__ether_simulation__clt_inst__mac_rx__crc_convert));
        Vether_simulation_MAC_rx___stl_comb__TOP__ether_simulation__clt_inst__mac_rx__1((&vlSymsp->TOP__ether_simulation__clt_inst__mac_rx));
        Vether_simulation_crc32_parallel_64bit___stl_comb__TOP__ether_simulation__clt_inst__mac_rx__CRC__0((&vlSymsp->TOP__ether_simulation__clt_inst__mac_rx__CRC));
    }
    if ((3ULL & vlSelfRef.__VstlTriggered.word(0U))) {
        Vether_simulation_MAC_rx___stl_comb__TOP__ether_simulation__svr_inst__mac_rx__0((&vlSymsp->TOP__ether_simulation__svr_inst__mac_rx));
        Vether_simulation___024root____Vm_traceActivitySetAll(vlSelf);
        Vether_simulation_top__CBz1___stl_comb__TOP__ether_simulation__svr_inst__0((&vlSymsp->TOP__ether_simulation__svr_inst));
        Vether_simulation_xgmii_little_to_big___stl_comb__TOP__ether_simulation__svr_inst__mac_rx__xgmii_cvrt__0((&vlSymsp->TOP__ether_simulation__svr_inst__mac_rx__xgmii_cvrt));
        Vether_simulation_xgmii_little_to_big___stl_comb__TOP__ether_simulation__svr_inst__mac_rx__crc_convert__0((&vlSymsp->TOP__ether_simulation__svr_inst__mac_rx__crc_convert));
        Vether_simulation_MAC_rx___stl_comb__TOP__ether_simulation__svr_inst__mac_rx__1((&vlSymsp->TOP__ether_simulation__svr_inst__mac_rx));
        Vether_simulation_crc32_parallel_64bit___stl_comb__TOP__ether_simulation__svr_inst__mac_rx__CRC__0((&vlSymsp->TOP__ether_simulation__svr_inst__mac_rx__CRC));
    }
}

VL_ATTR_COLD void Vether_simulation___024root___stl_sequent__TOP__0(Vether_simulation___024root* vlSelf) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vether_simulation___024root___stl_sequent__TOP__0\n"); );
    Vether_simulation__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    vlSymsp->TOP__ether_simulation.xgmii_rxc_clt = vlSelfRef.xgmii_rxc_clt;
    vlSymsp->TOP__ether_simulation.xgmii_rxd_clt = vlSelfRef.xgmii_rxd_clt;
    vlSelfRef.wr_FIFO_validing_svr = vlSymsp->TOP__ether_simulation.wr_FIFO_validing_svr;
    vlSymsp->TOP__ether_simulation.xgmii_rxc_svr = vlSelfRef.xgmii_rxc_svr;
    vlSymsp->TOP__ether_simulation.xgmii_rxd_svr = vlSelfRef.xgmii_rxd_svr;
    vlSymsp->TOP__ether_simulation.tb_count = vlSelfRef.tb_count;
    vlSymsp->TOP__ether_simulation.axis_r_en_clt = vlSelfRef.axis_r_en_clt;
    vlSymsp->TOP__ether_simulation.axis_r_en_svr = vlSelfRef.axis_r_en_svr;
    vlSymsp->TOP__ether_simulation.nRST = vlSelfRef.nRST;
    vlSymsp->TOP__ether_simulation.CLK = vlSelfRef.CLK;
    vlSymsp->TOP__ether_simulation.len_seq_clt = vlSelfRef.len_seq_clt;
    vlSymsp->TOP__ether_simulation.len_seq_svr = vlSelfRef.len_seq_svr;
    vlSymsp->TOP__ether_simulation.soupbin_TCP_payload_clt 
        = vlSelfRef.soupbin_TCP_payload_clt;
    vlSymsp->TOP__ether_simulation.wr_FIFO_en_clt = vlSelfRef.wr_FIFO_en_clt;
    vlSymsp->TOP__ether_simulation.axis_last_clt = vlSelfRef.axis_last_clt;
    vlSymsp->TOP__ether_simulation.soupbin_TCP_payload_svr 
        = vlSelfRef.soupbin_TCP_payload_svr;
    vlSymsp->TOP__ether_simulation.wr_FIFO_en_svr = vlSelfRef.wr_FIFO_en_svr;
    vlSymsp->TOP__ether_simulation.axis_last_svr = vlSelfRef.axis_last_svr;
    vlSymsp->TOP__ether_simulation.TX_en_clt = vlSelfRef.TX_en_clt;
    vlSymsp->TOP__ether_simulation.TX_en_svr = vlSelfRef.TX_en_svr;
    vlSymsp->TOP__ether_simulation.err_flag = vlSelfRef.err_flag;
    vlSymsp->TOP__ether_simulation.client_lost = vlSelfRef.client_lost;
    vlSymsp->TOP__ether_simulation.out_order = vlSelfRef.out_order;
    vlSymsp->TOP__ether_simulation.end_ss_clt = vlSelfRef.end_ss_clt;
    vlSymsp->TOP__ether_simulation.end_ss_svr = vlSelfRef.end_ss_svr;
}

VL_ATTR_COLD void Vether_simulation___024root___stl_sequent__TOP__1(Vether_simulation___024root* vlSelf) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vether_simulation___024root___stl_sequent__TOP__1\n"); );
    Vether_simulation__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    vlSelfRef.axis_rd_data_clt = vlSymsp->TOP__ether_simulation.axis_rd_data_clt;
    vlSelfRef.axis_r_valid_clt = vlSymsp->TOP__ether_simulation.axis_r_valid_clt;
    vlSelfRef.wr_FIFO_valid_clt = vlSymsp->TOP__ether_simulation.wr_FIFO_valid_clt;
    vlSelfRef.axis_rd_data_svr = vlSymsp->TOP__ether_simulation.axis_rd_data_svr;
    vlSelfRef.axis_r_valid_svr = vlSymsp->TOP__ether_simulation.axis_r_valid_svr;
}

VL_ATTR_COLD void Vether_simulation___024root___stl_sequent__TOP__2(Vether_simulation___024root* vlSelf) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vether_simulation___024root___stl_sequent__TOP__2\n"); );
    Vether_simulation__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    vlSelfRef.xgmii_txd_svr = vlSymsp->TOP__ether_simulation.xgmii_txd_svr;
    vlSelfRef.xgmii_txc_svr = vlSymsp->TOP__ether_simulation.xgmii_txc_svr;
    vlSelfRef.xgmii_txd_clt = vlSymsp->TOP__ether_simulation.xgmii_txd_clt;
    vlSelfRef.xgmii_txc_clt = vlSymsp->TOP__ether_simulation.xgmii_txc_clt;
}

VL_ATTR_COLD void Vether_simulation___024root___stl_sequent__TOP__3(Vether_simulation___024root* vlSelf) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vether_simulation___024root___stl_sequent__TOP__3\n"); );
    Vether_simulation__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    vlSelfRef.rcv_next_svr = vlSymsp->TOP__ether_simulation.rcv_next_svr;
    vlSelfRef.seq_num_svr = vlSymsp->TOP__ether_simulation.seq_num_svr;
    vlSelfRef.frame_end_svr = vlSymsp->TOP__ether_simulation.frame_end_svr;
    vlSelfRef.rcv_next_clt = vlSymsp->TOP__ether_simulation.rcv_next_clt;
    vlSelfRef.seq_num_clt = vlSymsp->TOP__ether_simulation.seq_num_clt;
    vlSelfRef.frame_end_clt = vlSymsp->TOP__ether_simulation.frame_end_clt;
}

VL_ATTR_COLD void Vether_simulation___024root___stl_sequent__TOP__4(Vether_simulation___024root* vlSelf) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vether_simulation___024root___stl_sequent__TOP__4\n"); );
    Vether_simulation__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    vlSelfRef.TCP_stop_flag_clt = vlSymsp->TOP__ether_simulation.TCP_stop_flag_clt;
    vlSelfRef.TCP_stop_flag_svr = vlSymsp->TOP__ether_simulation.TCP_stop_flag_svr;
}
