`include "receiver_pkg.vh"
`include "mac_ip_if.vh"

module ip_rx(
    input logic clk, nRST,
    mac_ip_if mipif
);   
    import receiver_pkg::*;
    state_t current_state, next_state;

    logic [DATA_SIZE-1:0] next_data, previous_data; 
    logic [BYTE_NUMBER-1:0] next_length; // this is generated by the header
    logic next_valid, next_start, next_end;
    
    count_t count, next_count; //64 bytes and 64 bits each time 

    always_ff @(posedge CLK, negedge nRST) begin
        if (!nRST) begin
            //output reset
            mipif.valid_udp <= 1'b0;
            mipif.data_udp <= '0;
            mipif.length_udp <= '0;
            mipif.start_udp <= 1'b0;
            mipif.end_udp <= 1'b0;
            next_state <= IDLE;

            //internal reset
            count <= '0;
        end else begin
            mipif.valid_udp <= next_valid;
            mipif.data_udp <= next_data;
            mipif.length_udp <= next_length;
            mipif.start_udp <= next_start;
            mipif.end_udp <= next_end;
            current_state <= next_state;
            count <= next_count;
        end
    end
    //todo fixed everything
    // implemnent the state machine logic
    always_comb begin
        next_data = mipif.data_mac; 
        next_length = mipif.length_mac; 
        next_valid = mipif.valid_mac;
        next_start = mipif.start_mac;
        next_end = mipif.end_mac;

        next_state = current_state; 
        next_count = count;
        case (current_state)
            IDLE: begin
                if (mipif.valid_mac) begin
                    next_state = HEADER;
                    next_count = '0; // Reset count when a new packet starts
                    next_start = 1'b1; // Start of a new packet
                end 
            end
            HEADER: begin
                if (mipif.valid_mac) begin
                    next_count = count + 1; 
                    case (count) 

                    endcase
                end else begin
                    next_state = ERROR; 
                end 
            end
            PAYLOAD: begin 
                if (mipif.valid_mac) begin
                    // Process data logic here
                    if (mipif.end_mac) begin
                        next_state = IDLE; // Go back to IDLE after processing data
                    end else begin
                        next_state = PAYLOAD; // Stay in PAYLOAD state
                    end
                end else begin
                    next_state = ERROR; 
                end
            end

            ERROR: begin
                if (mipif.valid_mac) begin
                    next_state = HEADER; // Go back to HEADER if a new packet is detected
                    next_start = 1'b1; // Start of a new packet
                end
            end   
            default: begin
                next_state = IDLE; // Fallback state
            end
        endcase
    end
endmodule