`include "receiver_pkg.vh"
`include "mac_ip_if.vh"

module ip_rx(
    input logic clk, nRST,
    mac_ip_if mipif
);   
    import receiver_pkg::*;
    state_t current_state, next_state;
    // include vlan active or not
    logic [DATA_SIZE-1:0] next_data, previous_data; 
    logic [BYTE_NUMBER-1:0] next_length; // this is generated by the header
    logic next_valid, next_start, next_end;

    logic [3:0] ip_version; // 4 bits for IP version, 4 bits for header length
    logic [7:0] ip_header_length; // 8 bits for header length, in bytes
    logic [7:0] ip_type; // 8 bits for IP type, e.g., IPv4 or IPv6
    logic [15:0] ip_total_length; // 16 bits for total length of the IP packet
    logic [15:0] ip_identification; // 16 bits for identification field
    logic [3:0] ip_flags; // 4 bits for flags
    logic [12:0] ip_fragment_offset; // 13 bits for fragment offset
    logic [7:0] ip_ttl; // 8 bits for Time to Live
    logic [7:0] ip_protocol; // 8 bits for protocol (TCP, UDP, etc.)
    logic [15:0] ip_header_checksum; // 16 bits for header checksum
    logic [31:0] ip_source_address; // 32 bits for source IP address
    logic [31:0] ip_destination_address; // 32 bits for destination IP address

    count_t count, next_count; //64 bytes and 64 bits each time 

    always_ff @(posedge CLK, negedge nRST) begin
        if (!nRST) begin
            //output reset
            mipif.valid_udp <= 1'b0;
            mipif.data_udp <= '0;
            mipif.length_udp <= '0;
            mipif.start_udp <= 1'b0;
            mipif.end_udp <= 1'b0;
            next_state <= IDLE;

            //internal reset
            count <= '0;
        end else begin
            mipif.valid_udp <= next_valid;
            mipif.data_udp <= next_data;
            mipif.length_udp <= next_length;
            mipif.start_udp <= next_start;
            mipif.end_udp <= next_end;
            current_state <= next_state;
            count <= next_count;
        end
    end
    //todo fixed everything
    // implemnent the state machine logic
    always_comb begin
        next_data = mipif.data_mac; 
        next_length = mipif.length_mac; 
        next_valid = 1'b0;
        next_start = 1'b0;
        next_end = 1'b0;

        next_state = current_state; 
        next_count = count;

        ip_version = '0; // Reset IP version
        ip_header_length = '0; // Reset header length
        ip_type = '0; // Reset IP type
        ip_total_length = '0; // Reset total length
        ip_identification = '0; // Reset identification field
        ip_flags = '0; // Reset flags
        ip_fragment_offset = '0; // Reset fragment offset           
        ip_ttl = '0; // Reset Time to Live
        ip_protocol = '0; // Reset protocol
        ip_header_checksum = '0; // Reset header checksum
        ip_source_address = '0; // Reset source IP address
        ip_destination_address = '0; // Reset destination IP address

        case (current_state)
            IDLE: begin
                if (mipif.valid_mac) begin
                    next_state = HEADER;
                    next_count = '0; // Reset count when a new packet starts
                    next_start = 1'b1; // Start of a new packet
                end 
            end
            // FINISH the EXCEL about timeing before finishing this part
            HEADER: begin
                if (mipif.valid_mac) begin
                    next_count = count + 1; 
                    case (count) 
                        // with VLAN, the first previous byte is IP type
                        // without VLAN, the first three bytes are IP type and addr  
                        0:  begin
                            if (mipif.vlan_active) begin
                                //todo check the order
                                ip_version = mipif.data_mac[59:56];
                                ip_header_length = mipif.data_mac[63:60];
                            end else begin
                                ip_version = mipif.data_mac[63:60];
                                ip_header_length = mipif.data_mac[59:56];
                                
                            end
                            if (ip_version != 4'b0100) begin
                                next_state = ERROR; // If not IPv4, go to ERROR state
                            end
                        end 
                        1: begin
                            if (mipif.vlan_active) begin
                                ip_type = mipif.data_mac[55:48]; // VLAN active, IP type is in the first byte
                            end else begin
                                ip_type = mipif.data_mac[55:48]; // IP type is in the first byte
                            end
                            ip_total_length = mipif.data_mac[47:32]; // Total length of the IP packet
                        end 
                        2: begin
                            // Only the first half the eight bytes are 
                            if (mipif.vlan_active) begin
                                ip_identification = mipif.data_mac[47:32]; // Identification field
                            end else begin
                                ip_identification = mipif.data_mac[31:16]; // Identification field
                            end
                        end
                    endcase
                end else begin
                    next_state = ERROR; 
                end 
            end
            PAYLOAD: begin 
                if (mipif.valid_mac) begin
                    // Process data logic here
                    if (mipif.end_mac) begin
                        next_state = IDLE; // Go back to IDLE after processing data
                    end else begin
                        next_state = PAYLOAD; // Stay in PAYLOAD state
                    end
                end else begin
                    next_state = ERROR; 
                end
            end

            ERROR: begin
                if (mipif.valid_mac) begin
                    next_state = HEADER; // Go back to HEADER if a new packet is detected
                    next_start = 1'b1; // Start of a new packet
                end
            end   
            default: begin
                next_state = IDLE; // Fallback state
            end
        endcase
    end
endmodule