`include "ip_udp_if.vh"
`include "receiver_pkg.vh"

module udp_rx (
    input logic clk, nRST,
    ip_udp_if_vh iuif
);
    // the checking logic of udp is simple, just check the length and the checksum
    import receiver_pkg::*;
    state_t current_state, next_state;
    logic [DATA_SIZE-1:0] next_data, previous_data; 
    logic [BYTE_NUMBER-1:0] next_length; // this is generated by the header
    logic next_valid, next_start;
    count_t count, next_count; 
    
    logic [15:0] udp_source_port, udp_destination_port; // 16 bits for source and destination ports
    logic [15:0] udp_length; // 16 bits for UDP length
    logic [15:0] udp_checksum; // 16 bits for UDP checksum

    always_ff @( posedge clk, negedge nRST) begin 
        if (!nRST) begin
            //output reset
            iuif.valid_udp <= 1'b0;
            iuif.data_udp <= '0;
            iuif.length_udp <= '0;
            iuif.start_udp <= 1'b0;
            // iuif.end_udp <= 1'b0;
            next_state <= IDLE;
            next_count <= '0;
        end else begin
            iuif.valid_udp <= next_valid;
            iuif.data_udp <= next_data;
            iuif.length_udp <= next_length;
            iuif.start_udp <= next_start;
            // iuif.end_udp <= next_end;
            current_state <= next_state;
            next_count <= count;
        end
    end

    always_comb begin
        next_data = iuif.data_ip;
        next_length = iuif.length_ip;
        next_valid = 1'b0;
        next_start = 1'b0;
        next_state = current_state;
        next_count = count + 1;
        case (current_state)
            IDLE: begin 
                if (iuif.valid_ip && iuif.start_ip) begin
                    next_state = HEADER;
                    next_count = '0; 
                    next_start = 1'b1; // start of a new UDP packet
                end
            end
            HEADER: begin // maybe this can be extended to be more stage
            //let's finish this verion first then improve the speed
                case (count) 
                    0: begin // MAC header
                        udp_destination_port = iuif.data_ip [31:16]; // 16 bits for destination port
                        udp_source_port = iuif.data_ip [47:32]; // 16 bits for source port
                        udp_length = iuif.data_ip [63:48]; // 16 bits for UDP length

                        if (udp_destination_port != UDP_DESTINATION || udp_source_port != UDP_SOURCE) begin
                            next_state = ERROR; 
                        end else if (udp_length < UDP_HEADER_LENGTH) begin
                            next_state = ERROR; // UDP length is less than header length
                        end 
                    end
                    1: begin
                        udp_checksum = iuif.data_ip [15:0]; 
                        //todo like ip layer figure about checksum logic
                        if (udp_checksum != UDP_CHECKSUM) begin
                            next_state = ERROR;
                        end else begin
                            next_state = PAYLOAD;
                            next_valid = 1'b1; 
                        end
                    end
                endcase
            end 
            PAYLOAD: begin
                if (iuif.valid_ip) begin
                    next_valid = 1'b1; // staying in PAYLOAD state
                end
                else if (iuif.end_ip) begin
                    next_state = IDLE; // end of the UDP packet
                end else begin
                    next_state = ERROR; // continue in PAYLOAD state
                end
            end
            ERROR: begin
                //todo check whether error statement is correct
                // if (iuif.end_ip) begin
                //     next_state = IDLE;
                // end 
                next_state = IDLE; // reset to IDLE state on error
            end
            default: begin
                next_state = IDLE; // default case to handle unexpected states
            end
        endcase
    end
endmodule